# coding: utf-8

"""
    Datasheets Backend

    This is Datasheet backend API documentation. This is intended only for development purposes

    The version of the OpenAPI document: 1.0.1
    Contact: kari.kolehmainen@vtt.fi
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from datasheets_openapi_client.models.benefits import Benefits  # noqa: E501

class TestBenefits(unittest.TestCase):
    """Benefits unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Benefits:
        """Test Benefits
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Benefits`
        """
        model = Benefits()  # noqa: E501
        if include_optional:
            return Benefits(
                operator = datasheets_openapi_client.models.benefit3_fields.Benefit3Fields(
                    1 = True, 
                    2 = True, 
                    3 = True, ),
                production = datasheets_openapi_client.models.benefit2_fields.Benefit2Fields(
                    1 = True, 
                    2 = True, ),
                quality = datasheets_openapi_client.models.benefit2_fields.Benefit2Fields(
                    1 = True, 
                    2 = True, ),
                machine = datasheets_openapi_client.models.benefit2_fields.Benefit2Fields(
                    1 = True, 
                    2 = True, )
            )
        else:
            return Benefits(
                operator = datasheets_openapi_client.models.benefit3_fields.Benefit3Fields(
                    1 = True, 
                    2 = True, 
                    3 = True, ),
                production = datasheets_openapi_client.models.benefit2_fields.Benefit2Fields(
                    1 = True, 
                    2 = True, ),
                quality = datasheets_openapi_client.models.benefit2_fields.Benefit2Fields(
                    1 = True, 
                    2 = True, ),
                machine = datasheets_openapi_client.models.benefit2_fields.Benefit2Fields(
                    1 = True, 
                    2 = True, ),
        )
        """

    def testBenefits(self):
        """Test Benefits"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
