# coding: utf-8

"""
    Datasheets Backend

    This is Datasheet backend API documentation. This is intended only for development purposes

    The version of the OpenAPI document: 1.0.1
    Contact: kari.kolehmainen@vtt.fi
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from datasheets_openapi_client.models.productiveaxis import Productiveaxis  # noqa: E501

class TestProductiveaxis(unittest.TestCase):
    """Productiveaxis unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Productiveaxis:
        """Test Productiveaxis
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Productiveaxis`
        """
        model = Productiveaxis()  # noqa: E501
        if include_optional:
            return Productiveaxis(
                ai_hri = True,
                ai_manualactivity = True,
                ai_quality = True
            )
        else:
            return Productiveaxis(
                ai_hri = True,
                ai_manualactivity = True,
                ai_quality = True,
        )
        """

    def testProductiveaxis(self):
        """Test Productiveaxis"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
