# coding: utf-8

"""
    Datasheets Backend

    This is Datasheet backend API documentation. This is intended only for development purposes

    The version of the OpenAPI document: 1.0.1
    Contact: kari.kolehmainen@vtt.fi
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from datasheets_openapi_client.models.technical_requirements import TechnicalRequirements  # noqa: E501

class TestTechnicalRequirements(unittest.TestCase):
    """TechnicalRequirements unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TechnicalRequirements:
        """Test TechnicalRequirements
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TechnicalRequirements`
        """
        model = TechnicalRequirements()  # noqa: E501
        if include_optional:
            return TechnicalRequirements(
                disk_unit = '',
                gpu_unit = '',
                multienancy_support = datasheets_openapi_client.models.requirement_support.RequirementSupport(
                    checkbox = True, ),
                multiuser_support = datasheets_openapi_client.models.requirement_support.RequirementSupport(
                    checkbox = True, ),
                ram_unit = '',
                dashboard = '',
                os = [
                    ''
                    ],
                protocol = [
                    datasheets_openapi_client.models.protocol_item.ProtocolItem(
                        name = '', )
                    ],
                requirement_cpu = '',
                requirement_disk = '',
                requirement_gpu = '',
                requirement_ram = ''
            )
        else:
            return TechnicalRequirements(
                disk_unit = '',
                gpu_unit = '',
                multienancy_support = datasheets_openapi_client.models.requirement_support.RequirementSupport(
                    checkbox = True, ),
                multiuser_support = datasheets_openapi_client.models.requirement_support.RequirementSupport(
                    checkbox = True, ),
                ram_unit = '',
        )
        """

    def testTechnicalRequirements(self):
        """Test TechnicalRequirements"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
