# coding: utf-8

"""
    Datasheets Backend

    This is Datasheet backend API documentation. This is intended only for development purposes

    The version of the OpenAPI document: 1.0.1
    Contact: kari.kolehmainen@vtt.fi
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from datasheets_openapi_client.models.hardware_dependency import HardwareDependency  # noqa: E501

class TestHardwareDependency(unittest.TestCase):
    """HardwareDependency unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HardwareDependency:
        """Test HardwareDependency
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HardwareDependency`
        """
        model = HardwareDependency()  # noqa: E501
        if include_optional:
            return HardwareDependency(
                dependency_level = '',
                module_link = '',
                device_text = ''
            )
        else:
            return HardwareDependency(
                dependency_level = '',
                module_link = '',
        )
        """

    def testHardwareDependency(self):
        """Test HardwareDependency"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
